import "./globals.css";
import { Play, Zen_Dots } from "next/font/google";
import Layout from "@/components/Templates/Layout";
import AuthLayout from "@/components/Templates/AuthLayout";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js"
};

const play = Play({
    weight: "400",
    subsets: ["latin"],
    variable: "--font-play",
    display: "swap"
});

const zenDots = Zen_Dots({
    weight: "400",
    subsets: ["latin"],
    variable: "--font-zen-dots",
    display: "swap"
});

export default function RootLayout({
    children
}: {
  children: React.ReactNode
}) {
    // TODO: Replace with real authentication logic
    const isAuthenticated = true;

    const SelectedLayout = isAuthenticated ? Layout : AuthLayout;

    return (
        <html lang={"en"} className={`${play.variable} ${zenDots.variable}`}>
            <body>
                <SelectedLayout>{children}</SelectedLayout>
            </body>
        </html>
    );
}
